#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int @__dad_dark_gray = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int @__dad_dark_gray_pressed = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int @__dad_darker_gray = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int @__dad_light_gray = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int dark_gray = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int dark_gray_pressed = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int darker_gray = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int light_gray = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int @__dad_actionbar_dimen = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_dimen = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int @__dad_drawer_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int drawer_content = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int drawer_indicator = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int drawer_layout = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int indicator_style = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int view_content = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppThemeNoBar = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
